version = 0.1

[default.deploy.parameters]
stack_name = "MTAToDCH"
resolve_s3 = true
s3_prefix = "MTAToDCH"
region = "ap-southeast-2"
profile = "exploren-aws-old"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
